name: Build PS5 Payload
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SDK Link
        run: |
          # إنشاء مجلد "أب" وهمي ليرى المترجم المسار الذي يتوقعه
          mkdir -p ../ps5-payload-sdk
          # إنشاء رابط رمزي يربط المجلد الفعلي بالمسار المتوقع
          ln -s $GITHUB_WORKSPACE/ps5-payload-sdk/include ../ps5-payload-sdk/include
          sudo apt-get update && sudo apt-get install -y clang lld

      - name: Compile
        run: |
          cd power_control
          make clean
          make

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Payload
          path: power_control/*.elf
